### ISSUE TITLE
Allow to pass options to esbuild 

### ISSUE THREAD

**Issue by umidbekk** [bahmutov/cypress-esbuild-preprocessor#11]
For example we can't run tests without these options:
```js
define: {
  global: 'globalThis',
  'process.env.NODE_ENV': JSON.stringify('production'),
},
```

**Comment by jgirardet** [comment]
same thing. I can't use this plugin with react.
I can use the other plugin (from sod) adding the following option:
```
define: { "process.env.NODE_ENV": '"development"' }
```
 to esbuildOptions

**Comment by jgirardet** [comment]
damned that was quick thanks :+1:
