### ISSUE TITLE
RFE: please add TypeScript definitions

### ISSUE THREAD

**Issue by kaiyoma** [bahmutov/cypress-esbuild-preprocessor#115]
Other Cypress and esbuild plugins offer TS definitions, which are always helpful.

**Comment by bahmutov** [comment]
:) whoever needs TS definitions is welcome to open a PR to add them of course

**Comment by JoaoTMDias** [comment]
Hey! I've opened a PR to address this, hope it helps :)

**Comment by kaiyoma** [comment]
@JoaoTMDias Is this still being worked on? The PR looks like it's stalled.

**Comment by JoaoTMDias** [comment]
Hey! I'm sorry I haven't been able to pay attention to this issue. I'll do the changes as soon as I can.

**Comment by illright** [comment]
This can be closed, type definitions have been added
