### ISSUE TITLE
How to add coverage

### ISSUE THREAD

**Issue by thednp** [bahmutov/cypress-esbuild-preprocessor#165]
I was using your previous @bahmutov/cy-rollup where it was fairly easy to implement, however, this package make a lot more sense. The following is not working:

```js
const createBundler = require('@bahmutov/cypress-esbuild-preprocessor');
const codeCoverageTasks = require('@cypress/code-coverage/task');

module.exports = (on, config) => {
  codeCoverageTasks(on, config);

  // pass ESBuild options to be applied to each spec file
  const bundler = createBundler({
    define: {
      "process.env.NODE_ENV": '"development"'
    }
  });
  on('file:preprocessor', bundler);

  // code coverage
  on('file:preprocessor', require('@cypress/code-coverage/use-babelrc'));

  // IMPORTANT to return the config object
  // with the any changed environment variables
  return config;
}
```

I'm getting 

```
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'
```

**Comment by thednp** [comment]
I'm looking at the [basic plugin example](https://github.com/bahmutov/cypress-esbuild-preprocessor/blob/main/cypress/plugins/index.js) now and trying to figure out a way to implement an instrumenter as a plugin, any idea how to approach this?

**Comment by hpierre74** [comment]
Hello @thednp 👋I see you implemented it in your [bootstrap.native repository](https://github.com/thednp/bootstrap.native), just sharing it there for others looking for it
