### ISSUE TITLE
Cypress-esbuild-preprocessor is causing chrome to crash with error 5

### ISSUE THREAD

**Issue by dqiubread** [bahmutov/cypress-esbuild-preprocessor#421]
Hey @bahmutov , with the newest version of cypress it seems like the preprocessor seems to be broken where Chrome will sometimes randomly crash with an error 5 and the polyfills dont seem to be working.

This is the error that happens.

We detected that the Chrome Renderer process just crashed. We have failed the current spec but will continue running the next spec. This can happen for a number of different reasons. If you're running lots of tests on a memory intense application. - Try increasing the CPU/memory on the machine you're running on. - Try enabling experimentalMemoryManagement in your config file. - Try lowering numTestsKeptInMemory in your config file during 'cypress open'. You can learn more here: https://on.cypress.io/renderer-process-crashed

**Comment by bahmutov** [comment]
:(Sent from my iPhoneOn Jul 19, 2024, at 14:04, dqiubread ***@***.***> wrote:﻿
Hey @bahmutov , with the newest version of cypress it seems like the preprocessor seems to be broken where Chrome will sometimes randomly crash with an error 5 and the polyfills dont seem to be working.
This is the error that happens.
We detected that the Chrome Renderer process just crashed. We have failed the current spec but will continue running the next spec. This can happen for a number of different reasons. If you're running lots of tests on a memory intense application. - Try increasing the CPU/memory on the machine you're running on. - Try enabling experimentalMemoryManagement in your config file. - Try lowering numTestsKeptInMemory in your config file during 'cypress open'. You can learn more here: https://on.cypress.io/renderer-process-crashed

**Comment by dqiubread** [comment]
Issue seems to be how we implemented our UI. Closing this as its working as intended.
